on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: -u oauth-atthaboon.s-04037:*****d99d --location \
              --request POST https://api.us-west-1.saucelabs.com/v1/storage/upload \
              --form payload=@"todo.zip" \
              --form 'name="todo.latest.app.zip"'
